//tealium universal tag - utag.1291 ut4.0.202105041310, Copyright 2021 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
var match=/ut\d\.(\d*)\..*/.exec(utag.cfg.v);if(utag.ut.loader===undefined||!match||parseInt(match[1])<41){u.loader=function(o,a,b,c,l,m){utag.DB(o);a=document;if(o.type=="iframe"){m=a.getElementById(o.id);if(m&&m.tagName=="IFRAME"){b=m;}else{b=a.createElement("iframe");}o.attrs=o.attrs||{};utag.ut.merge(o.attrs,{"height":"1","width":"1","style":"display:none"},0);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";}if(o.id){b.id=o.id;}for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState=="complete"||this.readyState=="loaded"){this.onreadystatechange=null;o.cb();}};}}if(o.type!="img"&&!m){l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}}};}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={"view":1,"link":1};u.initialized=false;u.scriptrequested=false;u.queue=[];u.clearEmptyKeys=function(object){for(var key in object){if(object[key]===""||object[key]===undefined){delete object[key];}}
return object;};u.map={"product_id":"WT.style_number","product_price":"WT.pn_p","product_upc":"WT.pn_sku","product_quantity":"wt.tx_u","search_keyword":"wt.oss","total_results":"wt.oss_r","unified_category":"wt.category_level2","top_level_category_id":"wt.category_level1","topLevelCategoryId":"wt.category_level1","customer_email_sha256":"EMAIL_HASH","page_type:order confirmation:trans_event_type":"p","page_type:browse:trans_event_type":"c","page_type:splash:trans_event_type":"c","page_type:sub-splash:trans_event_type":"c","page_type:product:trans_event_type":"v","page_type:product::WT.si_p":"View_Product","page_type:store locator:trans_event_type":"s","event_name:add to bag:trans_event_type":"a","event_name:add_to_bag:trans_event_type":"a","event_name:wishlist add:trans_event_type":"l","event_name:add_to_wishlist:trans_event_type":"l","order_id":"wt.tx_i","oracle_shipping_value":"WT.pn_ship","customer_postal_code":"WT.zipcode","oracle_search_facets":"WT.oss_filter","oracle_scenario_name":"wt.si_n","oracle_scenario_step":"wt.si_p","oracle_event":"wt.tx_e","oracle_wishlist_flag":"WT.z_list","oracle_save_flag":"wt.z_wishlist","order_promocode":"WT.z_promocode","product_sub_total":"wt.tx_s","oracle_store_flag":"WT.storedetails","store_id":"WT.storeid","action_misc":"WT.zipcode","oracle_conversion_step":"wt.si_cs","oracle_purchase_date":"wt.tx_id","oracle_purchase_time":"wt.tx_it","event_type:favourite add:trans_event_type":"l","order_email_sha256":"EMAIL_HASH"};u.extend=[function(a,b){try{if((typeof b['page_type']!='undefined'&&b['page_type'].toString().toLowerCase().indexOf('splash'.toLowerCase())>-1)||(typeof b['page_type']!='undefined'&&b['page_type'].toString().toLowerCase()=='browse'.toLowerCase())){b['unified_category']=b['category_id']}}catch(e){utag.DB(e);}},function(a,b){try{if((typeof b['page_type']!='undefined'&&b['page_type'].toString().toLowerCase()=='product'.toLowerCase())||(typeof b['page_type']!='undefined'&&b['page_type'].toString().toLowerCase()=='product quickview'.toLowerCase())){b['unified_category']=b['t_category_id']}}catch(e){utag.DB(e);}},function(a,b){try{if(1){if(b.shipping_value){if(b.shipping_value=='N/A')
{b.oracle_shipping_value='';}else{b.oracle_shipping_value=parseInt(b.shipping_value).toFixed(2);}}
if(b.event_name&&b.product_quantity&&b.product_price&&b.product_sub_total&&b.event_name=="add_to_bag"&&b.product_price=='0.00'){b.product_price=(b.product_sub_total/b.product_quantity).toFixed(2);}
if(b.event_name&&(b.event_name=='bag update'||b.event_name=='add_to_bag'||b.event_name=='add to bag'))
{b.product_sub_total='';}
if(b.page_type&&b.page_type=='shopping bag')
{b.product_sub_total='';}
if(typeof b.search_keyword=="undefined"){b.search_keyword=utag_data.search_keyword;}
if((b.page_type&&(b.page_type=='browse'||b.page_type=='splash'||b.page_type=='sub-splash')&&b.search_keyword)||(b.page_type&&(b.page_type=='browse'||b.page_type=='splash'||b.page_type=='sub-splash')&&b.category_id&&b.category_id=='onsite_search')||(b.page_type&&(b.page_type=='browse'||b.page_type=='splash'||b.page_type=='sub-splash')&&b["qp.cm_kws_ls"])||(b.page_type&&(b.page_type=='browse'||b.page_type=='splash'||b.page_type=='sub-splash')&&b["qp.cm_kws"]))
{b.page_type='search results';}
if(b.page_type&&(b.page_type=='browse'||b.page_type=='splash'||b.page_type=='sub-splash')){b.total_results='';}}}catch(e){utag.DB(e)}},function(a,b){try{if(1){if((b.facet_names&&b.facet_values&&b.event_name&&b.event_name=="product list updated"&&b.search_keyword)||(b.facet_names&&b.facet_values&&b.page_type&&b.page_type=="search results")||(b.facet_names&&b.facet_values&&b.category_id&&b.category_id=="onsite_search")){var facet_names=b.facet_names;var facet_values=b.facet_values;var values=[];for(var x=0;x<facet_values.length;x++){var facet_valuesArray=facet_values[x].split("|");for(var y=0;y<facet_valuesArray.length;y++){values.push(facet_names[x]+":"+facet_valuesArray[y]);}}
b.oracle_search_facets=values.join(";");}}}catch(e){utag.DB(e)}},function(a,b){try{if(1){if(b.event_name&&b.event_name=="bag update"&&(b.product_quantity<b.product_prev_quantity)){b.oracle_scenario_name="Commerce_Flow";b.oracle_scenario_step="Product_Cart_Remove";b.oracle_event="r";b.product_quantity=(b.product_prev_quantity-b.product_quantity);}else if(b.event_name&&b.event_name=="bag update"&&(b.product_quantity>b.product_prev_quantity)){b.oracle_scenario_name="Commerce_Flow";b.oracle_scenario_step="Product_Cart_Add";b.oracle_event="a";b.product_quantity=(b.product_quantity-b.product_prev_quantity);}
if(b.event_name&&b.event_name=="save for later add"&&b['dom.url'].toString().indexOf('/my-bag')>-1){b.oracle_scenario_name="Commerce_Flow";b.oracle_scenario_step="Product_Cart_Remove";b.oracle_save_flag="2";b.oracle_event="r";}
if(b.bag_add_location&&b.event_name&&b.bag_add_location=="save for later"&&b.event_name=="add_to_bag"){b.oracle_save_flag="3";b.oracle_event="w";}
if(b.event_name&&(b.event_name=="wishlist add"||b.event_name=="add_to_wishlist")&&b['dom.url'].toString().indexOf('/product/')>-1){b.oracle_wishlist_flag="1";b.oracle_event="l";}
if(b.event_type&&b.event_type=="favourite add"){b.oracle_wishlist_flag="1";b.oracle_event="l";}
if(b.event_name&&(b.event_name=="wishlist add"||b.event_name=="add_to_wishlist")&&b['dom.url'].toString().indexOf('/my-bag')>-1){b.oracle_scenario_name="Commerce_Flow";b.oracle_scenario_step="Product_Cart_Remove";b.oracle_wishlist_flag="2";b.oracle_event="l";}
if(b.event_name&&b.event_name=="add_to_bag"&&b['dom.url'].toString().indexOf('/wishlist/')>-1){b.oracle_wishlist_flag="3";b.oracle_event="l;a";}
if(b.page_type&&b.page_type=="order confirmation"){b.oracle_scenario_name="Commerce_Flow";b.oracle_scenario_step="Purchase_Complete";b.oracle_event="p";b.oracle_conversion_step="1";b.oracle_purchase_date=b.tealium_timestamp_local.substring(0,10);b.oracle_purchase_time=b.tealium_timestamp_local.substring(11,19);}
if(b.page_type&&b.page_type=="store locator"){b.oracle_event="s";if(b.page_name&&b.page_name!="State Landing Page"&&b.page_name!="Store Directory"&&b.page_name!="category store"&&b.page_name!="store search"){b.store_id=b.page_name;b.oracle_store_flag="1";}}}}catch(e){utag.DB(e)}},function(a,b){try{if((typeof b['page_type']!='undefined'&&b['page_type'].toString().toLowerCase()=='order confirmation'.toLowerCase())||(typeof b['page_type']!='undefined'&&b['page_type'].toString().toLowerCase()=='product'.toLowerCase())||(typeof b['event_name']!='undefined'&&b['event_name'].toString().toLowerCase()=='add to bag'.toLowerCase())||(typeof b['event_name']!='undefined'&&b['event_name'].toString().toLowerCase()=='add_to_bag'.toLowerCase())){b['oracle_scenario_name']='Commerce_Flow'}}catch(e){utag.DB(e);}},function(a,b,c,d,e,f,g){if((b['page_type'].toString().toLowerCase()=='product'.toLowerCase()&&typeof b['page_type']!='undefined')||(b['page_type'].toString().toLowerCase()=='order confirmation'.toLowerCase()&&typeof b['page_type']!='undefined')){d=b['page_type'];if(typeof d=='undefined')return;c=[{'product':'Product_View'},{'order confirmation':'Purchase_Complete'}];var m=false;for(e=0;e<c.length;e++){for(f in utag.loader.GV(c[e])){if(d==f){b['oracle_scenario_step']=c[e][f];m=true};};if(m)break};if(!m)b['oracle_scenario_step']='';}},function(a,b,c,d,e,f,g){if((b['event_name'].toString().toLowerCase()=='add to bag'.toLowerCase()&&typeof b['event_name']!='undefined')||(b['event_name'].toString().toLowerCase()=='add_to_bag'.toLowerCase()&&typeof b['event_name']!='undefined')){d=b['event_name'];if(typeof d=='undefined')return;c=[{'add to bag':'Product_Cart_Add'},{'add_to_bag':'Product_Cart_Add'}];var m=false;for(e=0;e<c.length;e++){for(f in utag.loader.GV(c[e])){if(d==f){b['oracle_scenario_step']=c[e][f];m=true};};if(m)break};if(!m)b['oracle_scenario_step']='';}},function(a,b){try{if((typeof b['page_type']!='undefined'&&b['page_type'].toString().toLowerCase()=='splash'.toLowerCase())||(typeof b['page_type']!='undefined'&&b['page_type'].toString().toLowerCase()=='sub-splash'.toLowerCase())||(typeof b['page_type']!='undefined'&&b['page_type'].toString().toLowerCase()=='browse'.toLowerCase())||(typeof b['page_type']!='undefined'&&b['page_type'].toString().toLowerCase()=='search results'.toLowerCase())||(typeof b['event_name']!='undefined'&&b['event_name'].toString().toLowerCase()=='product list updated'.toLowerCase())){try{b['product_id']=b.product_id.slice(0,5);}catch(e){}}}catch(e){utag.DB(e);}}];u.loader_cb=function(a,b,c){utag.DB("send:1291:CALLBACK");u.initialized=true;var key,params={"config":{"callbacks":{"success":u.data.successCallback,"fail":u.data.failCallback},"mutation":u.data.mutation}};if(u.data.oi_data["wt.tx_cartid"]&&!u.data.transaction_event_type){u.data.oi_data["wt.tx_e"]="p";}else if(u.data.transaction_event_type){u.data.oi_data["wt.tx_e"]=u.data.transaction_event_type;}
params["data"]=u.data.oi_data;for(key in params.data){if(params.data.hasOwnProperty(key)&&utag.ut.typeOf(params.data[key])==="array"){params.data[key]=params.data[key].join(u.data.delimiter);}}
params.data=u.clearEmptyKeys(params.data);if(!window.ORA){window.ORA={productReady:[]};}
if(a==="link"){ORA.productReady.push(['analytics',function(){ORA.click(params)}]);}else if(a==="view"){ORA.productReady.push(['analytics',function(){ORA.view(params)}]);}
utag.DB("send:1291:CALLBACK:COMPLETE");};u.callBack=function(){var data={};while(data=u.queue.shift()){u.data=data.data;u.loader_cb(data.a,data.b,data.c);}};u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){utag.DB("send:1291");utag.DB(b);var c,d,e,f,h;u.data={"delimiter":";","base_url":"//c.oracleinfinity.io/acs/account/##utagreplace_account_guid##/js/##utagreplace_tag_id##/odc.js","account_guid":"b8329d0ce88880c0e053ae14000a63e5","tag_id":"macys","context":"","successCallback":null,"failCallback":null,"mutation":null,"oi_data":{"wt.pn_id":[],"wt.pn_sku":[],"wt.tx_u":[]},"transaction_event_type":""};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};utag.DB("send:1291:EXTENSIONS");utag.DB(b);for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(u.data.hasOwnProperty(e[f])){u.data[e[f]]=b[d];}else{u.data.oi_data[e[f]]=b[d];}}}else{h=d.split(":");if(h.length===3&&b[h[0]]===h[1]){if(u.map[d]){u.data.transaction_event_type=u.map[d];}}}}
utag.DB("send:1291:MAPPINGS");utag.DB(u.data);u.data.oi_data["wt.tx_cartid"]=u.data.oi_data["wt.tx_cartid"]||b._corder||"";if(u.data.oi_data["wt.pn_id"].length===0&&b._cprod!==undefined){u.data.oi_data["wt.pn_id"]=b._cprod.slice(0);}
if(u.data.oi_data["wt.pn_sku"].length===0&&b._csku!==undefined){u.data.oi_data["wt.pn_sku"]=b._csku.slice(0);}
if(u.data.oi_data["wt.tx_u"].length===0&&b._cquan!==undefined){u.data.oi_data["wt.tx_u"]=b._cquan.slice(0);}
if(!u.data.account_guid){utag.DB(u.id+": Tag not fired: Required attribute account_guid not populated");return;}
if(!u.data.tag_id){utag.DB(u.id+": Tag not fired: Required attribute tag_id not populated");return;}
u.data.base_url=u.data.base_url.replace("##utagreplace_account_guid##",u.data.account_guid);u.data.base_url=u.data.base_url.replace("##utagreplace_tag_id##",u.data.tag_id);if(u.data.context){u.data.base_url+=u.data.context.match("^analytics:")?("?_ora.context="+u.data.context):("?_ora.context=analytics:"+u.data.context);}
if(u.initialized){u.loader_cb(a,b,c);}else{u.queue.push({"data":u.data,"a":a,"b":b,"c":c});if(!u.scriptrequested){u.scriptrequested=true;u.loader({"type":"script","src":u.data.base_url,"cb":u.callBack,"loc":"script","id":"utag_1291","attrs":{}});}}
utag.DB("send:1291:COMPLETE");}};utag.o[loader].loader.LOAD(id);}("1291","macys.main"));}catch(error){utag.DB(error);}
